use ncp;

SELECT MAX(CAST(CODE AS SIGNED INTEGER) - CAST('11000' AS SIGNED INTEGER)) AS MAX
FROM PROGRAM_INFORMATION
WHERE CAST(CODE AS SIGNED INTEGER) BETWEEN CAST('11000' AS SIGNED INTEGER) AND CAST('11000' AS SIGNED INTEGER) + 999;